apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod 
spec:
  volumes:
  - name: shared-volume
    emptyDir: {}  
  containers:
  - name: container-one
    image: busybox
    command: ['sh', '-c', 'echo Hello from Container One > /usr/share/message/message.txt && sleep 3600']
    volumeMounts:
    - name: shared-volume
      mountPath: /usr/share/message
  - name: container-two
    image: busybox  
    command: ['sh', '-c', 'cat /usr/share/message/message.txt && sleep 3600']
    volumeMounts: 
    - name: shared-volume
      mountPath: /usr/share/message
