apiVersion: v1
kind: Pod
metadata:
  name: simple-pod-with-volume  
spec:
  containers:
    - name: simple-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: simple-volume
  volumes:
    - name: simple-volume
      emptyDir: {}
      sizeLimit: "1Gi"