apiVersion: v1 
kind: Pod
metadata:
  name: non-privileged-pod
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 2000
    fsGroup: 3000
  containers:
  - name: non-privileged-container
    image: nginx:latest
    
    