apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-allow-get
  namespace: default
subjects:
# Define the subject (user, group, or service account) to bind the role to
- kind: User
  name: jane-doe
  # Specify the API group for the subject
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: allow-get
  apiGroup: rbac.authorization.k8s.io 
