apiVersion: v1
kind: Pod 
metadata:
  name: pod-with-mounted-secret 
spec:
  containers:
    - name: mycontainer
      image: nginx
      volumeMounts:
        - name: secret-volume
          mountPath: "/etc/secret-data"
          readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: my-secret 
        items:
          - key: username
            path: username.txt
          - key: password
            path: password.txt
  restartPolicy: Never  