apiVersion: v1
kind: Pod 
metadata:
  name: pod-with-mounted-secret 
spec:
  containers:
    - name: mycontainer
      image: nginx
      env: 
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: username
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: password
  restartPolicy: Never  